### ISSUE TITLE
Incorrect result when b is not bool/integer

### ISSUE THREAD

**Issue by Kazath-git** [ieShie1f/true#1]
There's an issue with isTrue when b is not a boolean, an integer, or a class with proper magic methods.

For example, isTrue("Hello World") returns True even if "Hello World" doesn't equals to True. Same with lists, functions, etc.

Fortunately, you can solve the issue by stating there's other cases using ellipsis in recursion :

```
        # otherwise: solve the problem recursively
        return isTrue(not b) == (False or ...)
```

It seems to solve all issues. Could you consider adding it as a patch?

I find your module really useful, thanks for the hard work!

**Comment by ieShie1f** [comment]
Fixed in aec3aba62954e3df514bbda71c6ec57c5e6b82e6
I love this elegant solution that uses ellipsis.
